output "instance_id" { value = aws_instance.satellite.id }
output "private_ip" { value = aws_instance.satellite.private_ip }
output "public_ip" { value = aws_instance.satellite.public_ip }
output "satellite_fqdn" { value = local.satellite_fqdn }
output "pulp_volume_id" { value = aws_ebs_volume.pulp.id }
output "provisioning_subnet_id" { value = aws_subnet.provisioning.id }
output "provisioning_subnet_name" { value = aws_subnet.provisioning.tags["Name"] }
output "provisioning_subnet_cidr" { value = aws_subnet.provisioning.cidr_block }
output "provisioning_subnet_network" { value = cidrhost(aws_subnet.provisioning.cidr_block, 0) }
output "provisioning_subnet_mask" { value = cidrnetmask(aws_subnet.provisioning.cidr_block) }
output "provisioning_subnet_gateway" { value = cidrhost(aws_subnet.provisioning.cidr_block, 1) }
output "provisioning_subnet_dns" { value = cidrhost(data.aws_vpc.selected.cidr_block, 2) }
output "ssm_start_session" { value = "aws ssm start-session --target ${aws_instance.satellite.id} --region ${var.aws_region}" }
